### PR TITLE
Add Nix build, `grepl` Docker image generation

### PR DESCRIPTION
**Pull request by raehik**
I have convenient slim Docker image generation with no funny business (no Dockerfile!) over on [camfort/camfort](https://github.com/camfort/camfort). It leverages the [Nix package manager](https://nixos.org/), which I+the CI already use to build. @dorchard expressed interest in doing the same for Granule for an easy Docker image.

Some notes:

* I add a `cabal.project` because Nix builds with Cabal: nice and simple thankfully
* I commit `*.cabal` files because Nix needs them in repo. Stack creator recommends this practice as of a few years ago: https://www.fpcomplete.com/blog/storing-generated-cabal-files/
* This is easily shoved into a CI job so no one has to look at Nix or wrangle images unless (well, until) the build breaks. See: https://github.com/camfort/camfort/blob/d4f8008b720b67e8fe8ddf9f4158c11fa5c405c3/.github/workflows/nix.yaml (I never wrote automated image managing, so you'd still have to retag stuff, but it's complete otherwise.)

Temporary image at `docker.io/raehik/granule-repl:dev-minor`. Try with:

    docker run --interactive docker.io/raehik/granule-repl:dev-minor

(Replace `docker` with `podman` if you're anti-Docker like myself.)

### CODE REVIEW

**Comment by raehik** [comment]
Some notes:

  * I'd update the build/install instructions @ https://github.com/granule-project/granule/wiki/Installing-Granule , but I don't have permissions.
  * I haven't added any CI.
  * We probably could cross-compile for ARM64: https://discourse.nixos.org/t/nix-github-actions-aarch64/11034/4

**Comment by raehik** [comment]
Now merging to `main` because `dev-minor` was merged in earlier.

**Comment by raehik** [comment]
GitHub is a better container registry than Docker now. Someone with admin rights on the granule-project org should be able to go to https://github.com/orgs/granule-project/packages to create a new registry, then get creds to push images. I could then plug in my Nix CI that auto-builds, auto-pushes for every commit. (Ping me anywhere I'm reachable if you want a hand.)

**Comment by jackohughes** [comment]
> GitHub is a better container registry than Docker now. Someone with admin rights on the granule-project org should be able to go to https://github.com/orgs/granule-project/packages to create a new registry, then get creds to push images. I could then plug in my Nix CI that auto-builds, auto-pushes for every commit. (Ping me anywhere I'm reachable if you want a hand.)

@dorchard I believe you might be the only one with the rights to do this? I can update the instructions for installing Granule!

**Comment by raehik** [comment]
I'd want to add a brief section on building/running components using Cabal, and using Nix, then building the `grepl` Docker image using Nix, then running the `grepl` Docker image (especially where it's stored).

**Pull request merged**
