### PR TITLE
Compiler

### PR DESCRIPTION
**Pull request by edwardb96**
Duplicate of #121, with `compiler` branch rather than `compiler-emit-llvm` which is slightly out of date and not needed anymore.

From #121
> I believe this is the branch containing the latest work on the compiler? I propose we merge this now 
> before things get too stale.

### CODE REVIEW

**Comment by dorchard** [comment]
Thanks Ed. I'll take a look at these conflicts today.

**Comment by edwardb96** [comment]
I believe this is ready to go?

**Comment by dorchard** [comment]
This looks all fine to me apart from a change in frontend/src/Language/Granule/Syntax/Def.hs on line 82:

      returnTy t [] = t
      returnTy t (v:vs) = returnTy (TyApp t ((TyVar . fst) v)) vs

is replaced with

      returnTy t vs = foldl (\t v -> returnTy (TyApp t ((TyVar . fst) v)) vs) t vs

Which looks suspicious to me: a recursion inside of the fold is suspicious - it seems like this would do redundant computation: should the inner `returnTy` even be there?

**Comment by edwardb96** [comment]
I think HLint suggested it and I just blindly clicked the 'apply hint' button without really thinking about it :man_facepalming:.

**Pull request merged**
