### PR TITLE
allow kinds to be ommited in type schemes, and automatically resolve …

### PR DESCRIPTION
**Pull request by buggymcbugfix**
…them; plus some refactoring

### CODE REVIEW

**Comment by buggymcbugfix** [comment]
@dorchard freshening seems to dissociate the kind variable you introduce here: https://github.com/granule-project/granule/pull/104/files#diff-ae699d8ac617e09772ee04f60987c697R271

Is this intended?

**Example**

Input:

```agda
id : forall a . a -> a
id x = x
```

After freshening:

```agda
id : forall a`0 : _ka, _ka`1 : ↑Kind. a`0 -> a`0
id x`2 = x`2
```

In my mind we want `_ka` and ``_ka`1`` to be the same.

**Comment by buggymcbugfix** [comment]
The following doesn't seem to work, but I believe it should:

```agda
data Fix (f : Type -> Type) = Fix (f (Fix f))

unfix : forall a f . Fix f -> f (Fix f)
unfix (Fix x) = x
```

> Kind mismatch: StdLib/Fix.gr:13:1:
> Expected kind `. -> .` but got `_kf`

**Comment by dorchard** [comment]
Thanks. Yes that looks like a freshening bug, and the second I know how to improve the power of the inference to allow this. At least none of the paper examples require it. 
 
I would rather keep all the kinds explicit in the standard library (more documentation essentially).

**Comment by buggymcbugfix** [comment]
I'm surprised that this works despite the freshening bug. Do you have an intuition why or is this indicative of a bug somewhere that is letting this go through?

**Comment by dorchard** [comment]
I think I know why- I think its because the additional `_kn1 : Kind` quantification is not actually needed. but I will investigate.

**Comment by buggymcbugfix** [comment]
@dorchard I agree that it might make sense to keep the kind annotation for the `f` type variable in the `Fix` case, but it would be great if we could infer it nevertheless, so I have added it as a test case.

I had removed the kind annotations from the `Nat` and `Vec` modules, which reduces line noise IMO. Do you want me to revert it?

**Comment by dorchard** [comment]
Yes I think it would be good to keep explicit signature in the standard library. Especially when they pertain to coeffects.

**Comment by dorchard** [comment]
The other issues you mentioned are fixed now.

**Pull request merged**
