### PR TITLE
WIP: Initial implementation of Interfaces

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
# Moved to Pull Request #95

See [work-in-progress/interface.gr](https://github.com/GuiltyDolphin/granule/blob/gd/interface-syntax/work-in-progress/interface.gr) for some ideas on syntax/semantics to be implemented.

### Todo

- [x] syntax
  - [x] interfaces `interface NAME a where`
  - [x] instances `instance IFACE NAME where`
  - [x] constraints
    - [x] in functions: `f : forall (a : Type) . {IFACE a} => a -> a`
    - [x] in interfaces: `interface (IFACE a) => NAME a where`
    - [x] in instances: `instance (IFACE a) => IFACE (NAME a) where`
    - [x] multiple: e.g., `f : forall (a : Type) . {IFACE0 a, IFACE1 a} => a -> a`

#### Future

- [ ] named instances
  - [ ] `instance IFACE DAT named NAME` syntax
  - [ ] `instance IFACE DAT using NAME` syntax
  - [ ] `instance IFACE DAT named NAME using NAME` syntax

### CODE REVIEW

**Comment by buggymcbugfix** [comment]
Hey Ben, good to see you on here! :)

Some observations/questions:

- How are you intending to implement interfaces? Dictionary passing or compile-time resolution and specialisation?
- We do support infix function application using back ticks, like Haskell, so you can write ``a `op` b``.
- I feel we should either stick to `class/instance` _or_ `interface/implementation` unless you have a good reason to start a new convention.

**Comment by buggymcbugfix** [comment]
Hey @GuiltyDolphin, any updates on this?

**Comment by buggymcbugfix** [comment]
Related read if you're up for it https://people.cs.kuleuven.be/~tom.schrijvers/Research/papers/jfp2019.pdf

**Comment by buggymcbugfix** [comment]
More related reading: http://repetae.net/recent/out/classalias.html

**Comment by apoorvingle** [comment]
> Related read if you're up for it https://people.cs.kuleuven.be/~tom.schrijvers/Research/papers/jfp2019.pdf

Is this the same as the Implicit  in Scala programming language if anyone has used it?

**Comment by buggymcbugfix** [comment]
@apoorvingle I can't remember exactly off the top of my head, but Scala was mentioned, and I think they have something which can express what Scala has, but don't take my word for it. :)

**Comment by dorchard** [comment]
Yeah, I'm a bit wary of going to full Scala-style implicits. At the moment we're going for ambient coeffect style constraints (like GHC class constraints) which get discharged automatically by the compiler. The constraints can be class constraints (like Haskell type classes) or they can be theorems which the type checker must solve, e.g.

```
headEq : forall a : Type, n : Nat . {Eq a, n > 0} -> (Vec n a) [0..1] -> a -> Bool
headEq [Cons x _] y = x == y
```
@GuiltyDolphin is working on the type classes (styled as interfaces like Idris) which at some point will get unified with the `predicates` work-in-progress branch that allows additional constraints `n > 0` to be added.

**Comment by GuiltyDolphin** [comment]
New branch: https://github.com/granule-project/granule/tree/gd/interface-syntax

**Pull request closed without merging**
